# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches:
      - main

      
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
            
    - name: Test       
      run: go test -v -coverprofile=coverage.out -covermode=count ./...
      continue-on-error: true
    
    
    - name: Go Patch Coverage
      uses: seriousben/go-patch-cover-action@v1.1.2
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
          version: v1.54
          github_token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

            
  
